name: .NET Core Desktop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAME: BreadcrumbsCFSDev.Backend.Infra.Base.Interfaces
      TPATH: /home/runner/work/CFSDev.Backend.Infra.Base.Interfaces/CFSDev.Backend.Infra.Base.Interfaces/CFSDev.Beckend.Infra.Base.Interfaces
      VERSION: 1.0.0

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./Backend.Infra.Base.Interfaces.csproj
      - name: Build
        run: dotnet build --no-restore ./Backend.Infra.Base.Interfaces.csproj
      - name: Pack
        run: dotnet pack -o ./ ./Backend.Infra.Base.Interfaces.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - name: Publish
        run: nuget push ${{env.TPATH}}.${{env.VERSION}}.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.MAIN}} -SkipDuplicate
